services:
  serenity-discord-bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - ./extra_utils:/app/extra_utils
    networks:
      - bot-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  bot-network:
    driver: bridge
